export const UPDATE_BLOCKS = "UPDATE_BLOCKS";
export const PERSIST_BLOCKS = "PERSIST_BLOCKS";
export const FETCH_BLOCKS_FROM_STORAGE = "FETCH_BLOCKS_FROM_STORAGE";
export const PERSIST_BLOCKS_TO_STORAGE = "PERSIST_BLOCKS_TO_STORAGE";